In [11]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [13]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [14]:
len(X_train)

22

In [15]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [16]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [17]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled,y_train,epochs=500)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 422ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - los

In [18]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 256ms/step - accuracy: 0.6667 - loss: 0.6210


[0.621041476726532, 0.6666666865348816]

In [19]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [20]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


array([[0.66075516],
       [0.6084721 ],
       [0.45149702],
       [0.62685424],
       [0.6642366 ],
       [0.68474233]], dtype=float32)

In [21]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [22]:
coef , intercept = model.get_weights()
coef , intercept

(array([[0.77850705],
        [0.6977987 ]], dtype=float32),
 array([-0.39703575], dtype=float32))

In [23]:
def sigmoid(x):
  import math
  return 1 / (1+math.exp(-x))

sigmoid(18)

0.9999999847700205

In [24]:
def prediction_function(age,affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)

In [25]:
prediction_function(0.47,1)

<ipython-input-23-48f263bf5fe3>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1+math.exp(-x))


0.6607551841052955

In [26]:
prediction_function(0.18,1)

<ipython-input-23-48f263bf5fe3>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1+math.exp(-x))


0.608472098150997

In [27]:
def log_loss(y_true,y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [28]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [45]:
class myNN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0

  def fit(self,X,y,epochs,loss_threshold):
    self.w1 , self.w2 , self.bias = self.gradient_descent_function(X['age'],X['affordibility'],y,epochs,loss_threshold)

  def predict(self,X_test):
    weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
    return sigmoid_numpy(weighted_sum)


  def gradient_descent_function(self,age,affordibility,y_true,epochs,loss_threshold):
  # w1 , w2 , bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n=len(age)

    for i in range(epochs):
      weighted_sum = w1 * age + w2 * affordibility + bias
      y_predicted = sigmoid_numpy(weighted_sum)

      loss = log_loss(y_true,y_predicted)

      w1d = (1/n)*(np.dot(np.transpose(age),(y_predicted-y_true)))
      w2d = (1/n)*(np.dot(np.transpose(affordibility),(y_predicted-y_true)))

      bias_d = np.mean(y_predicted - y_true)

      w1 = w1 - rate * w1d
      w2 = w2 - rate * w2d
      bias = bias - rate * bias_d

      if i%50==0:
        print(f'Epoch : {i} , w1 : {w1} , w2 : {w2} , bias : {bias} , loss : {loss}')

      if loss <= loss_threshold:
        print(f'Epoch : {i} , w1 : {w1} , w2 : {w2} , bias : {bias} , loss : {loss}')
        break

    return w1 , w2 , bias


In [48]:
customModel = myNN()
customModel.fit(X_train_scaled , y_train , epochs=500 , loss_threshold=0.4631)

Epoch : 0 , w1 : 0.974907633470177 , w2 : 0.948348125394529 , bias : -0.11341867736368583 , loss : 0.7113403233723417
Epoch : 50 , w1 : 1.503319554173139 , w2 : 1.108384790367645 , bias : -1.2319047301235464 , loss : 0.5675865113475955
Epoch : 100 , w1 : 2.200713131760032 , w2 : 1.2941584023238903 , bias : -1.6607009122062801 , loss : 0.5390680417774752
Epoch : 150 , w1 : 2.8495727769689085 , w2 : 1.3696895491572747 , bias : -1.986105845859897 , loss : 0.5176462164249293
Epoch : 200 , w1 : 3.443016970881804 , w2 : 1.404221862446503 , bias : -2.2571369883752723 , loss : 0.5005011269691374
Epoch : 250 , w1 : 3.982450494649577 , w2 : 1.423912732932123 , bias : -2.494377365971801 , loss : 0.48654089537617085
Epoch : 300 , w1 : 4.4721795220959155 , w2 : 1.438787986553552 , bias : -2.7073878119223735 , loss : 0.47508146406327917
Epoch : 350 , w1 : 4.917245868007634 , w2 : 1.4525660781176122 , bias : -2.901176333556766 , loss : 0.46561475306999006
Epoch : 366 , w1 : 5.051047623653049 , w2 : 1

In [49]:
customModel.predict(X_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

In [50]:
model.predict(X_test_scaled )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[0.66075516],
       [0.6084721 ],
       [0.45149702],
       [0.62685424],
       [0.6642366 ],
       [0.68474233]], dtype=float32)